language: node_js

node_js:
  - 10
  - 12

jobs:
  include:
    - stage: Linting
      script: npm run lint
    - stage: Deploy
      script: skip
      on:
        tags: true
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
